### ISSUE TITLE
Crash SyntaxError: Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by schnub69** [ageorgios/homebridge-sonoff-tasmota-http#14]
New Homebridge with only Tasmota-http and keeps crashin.

Got them working after system died a day ago.

All Sonoffs got Tasmota 5.9.0

can some 1 help? 

Update: Updated all Sonoff Devices to 6.2.1 no the Homebridge starts normally but all devices has "no response" :( 

this must be to do something with this package. deleting this will keep homebridge working. 

Error:

ERGEBNIS = {"POWER":"OFF"}
^

SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/homebridge-sonoff-tasmota-http/index.js:33:29)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sonoff-tasmota-http/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sonoff-tasmota-http/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sonoff-tasmota-http/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)

**Comment by ageorgios** [comment]
The Tasmota compatible version of the plugin is 5.11.0 and later

If you need compatibility with previous Tasmota versions, fork this commit: https://github.com/ageorgios/homebridge-sonoff-tasmota-http/tree/6f73a32fd8ae01f16813f8f0bd3844d3da469e4d

It is also tested only in English
